name: 'deploy-builds-action'
description: 'deploy builds to a github builds repo'
runs:
  using: 'node12'
  main: 'lib/index.js'
inputs:
  files:
    description: 'files to be deployed'
    required: true
